#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::indexAction

show_skill:
  path: /skill/{id}/show
  controller: App\Controller\SkillController::showAction

show_techno:
  path: /techno/{id}/show
  controller: App\Controller\TechnoController::showAction

dashboard:
  path: /admin/dashboard
  controller: App\Controller\Admin\DashboardController::indexAction

dashboard_list_categories:
  path: /admin/dashboard/categories/list
  controller: App\Controller\Admin\Categories\CategoriesAdminController::listAction

dashboard_create_category:
  path: /admin/dashboard/category/new
  controller: App\Controller\Admin\Categories\CategoriesAdminController::newAction

dashboard_update_category:
  path: /admin/dashboard/category/{id}/update
  controller: App\Controller\Admin\Categories\CategoriesAdminController::updateAction

dashboard_delete_category:
  path: /admin/dashboard/category/{id}/delete
  controller: App\Controller\Admin\Categories\CategoriesAdminController::deleteAction

dashboard_list_technos:
  path: /admin/dashboard/technos/list
  controller: App\Controller\Admin\Technos\TechnosAdminController::listAction

dashboard_create_techno:
  path: /admin/dashboard/techno/new
  controller: App\Controller\Admin\Technos\TechnosAdminController::newAction
