#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::indexAction

show_skill:
  path: /skill/{id}/show
  controller: App\Controller\SkillController::showAction

